export interface InfoButtonModel {
	onClick: (event: React.MouseEvent<HTMLElement, MouseEvent>) => void
	style?: React.CSSProperties
}

export function InfoButton(model: InfoButtonModel) {
	return <img src='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QAAKqNIzIAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAAHdElNRQfjCw0JEwsgUonVAAABAklEQVQoz13RO05CURgE4A9j0Fi5ALWiAxNrLTQYK2EDrsCoIQQLVyGgEd2FvYkoUmuFboAACxBiw/VR3MMFnGpm/jP5H4cJNl15NzLyri5nDktufWspKygoa/nWkJ6Wn/TszUXy+pqTJ3d61vzHur6buHeUpE91dZ0EtS+Spe45GDvGSkrGtoPTVuVDOcgzD+DNeXAqOgwdBrlgxapjY7vBKfpcRCrIH18uHbnwEpyU3wVdmZnZl92rJiqjm1K3NXODXZI8ba/kRPKJVVNL+EG8Jg1968lYxcA2DFzHNK2pb3/ujgcGHqe/kXYj0lZRVHSuLXI9LcfIquoYGuqoxr3hD8/gSWgYBpCxAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDE5LTExLTEzVDA5OjE5OjExKzAwOjAwGCosaAAAACV0RVh0ZGF0ZTptb2RpZnkAMjAxOS0xMS0xM1QwOToxOToxMSswMDowMGl3lNQAAAAZdEVYdFNvZnR3YXJlAHd3dy5pbmtzY2FwZS5vcmeb7jwaAAAAAElFTkSuQmCC' style={{ verticalAlign: 'bottom', marginLeft: '5px', ...model.style }} onClick={model.onClick} />
}
