// THIS FILE IS AUTOGENERATED DURING MIGRATION, DO NOT EDIT BY HAND
pragma solidity 0.5.12;

import { IERC20 } from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import { DaiJoin } from "./join.sol";
import { Pot } from "./pot.sol";
import { Vat } from "./vat.sol";

contract RuntimeConstants {
	IERC20 constant public dai = IERC20(0x96883f74Cde12BB0889156f733F5fc9cbF16873d);
	Pot constant public pot = Pot(0xBAa6fDc76f1963E10835535A83111d40303fCE41);
	DaiJoin constant public daiJoin = DaiJoin(0xF4fB7Ca5A47465d4f48BF92C444c862E50F22904);
	Vat constant public vat = Vat(0xA1cD2398618FF8DD73ED244a02273284188f228C);
	address constant public uniswapExchange = 0x4f6fcD7041022Dd8c4BA56fF4de19FA0F1BC8612;
}
