// THIS FILE IS AUTOGENERATED DURING MIGRATION, DO NOT EDIT BY HAND
	pragma solidity 0.5.12;

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "./DaiJoinLike.sol";
import "./PotLike.sol";
import "./VatLike.sol";

contract RuntimeConstants {
	IERC20 constant public dai = IERC20(0xB5166996fA4F1e913F4b3fc670d808Fed977dA01);
	PotLike constant public pot = PotLike(0x84EB276362b29bD97E146317cc9C0853CD775f83);
	DaiJoinLike constant public daiJoin = DaiJoinLike(0x4Ae6d0e8Ffe7e83601563e6637df084f50c13BB3);
	VatLike constant public vat = VatLike(0x3811C7E29330D126Db886E533ee78939c5FaC128);
	address constant public uniswapExchange = 0x5867165fdf9fA672EE02AaF0fE57Ef316E0DAF26;
}
